using System.Collections.Immutable;
using System.CommandLine;

namespace IviCli.Cli.Completion;

/// <summary>
/// Pure helper that walks a <see cref="Command"/> tree and resolves
/// completion candidates for a partially-typed command line. Used by
/// <c>ivicli __complete</c> to drive the bash / zsh / PowerShell stub
/// generated by <c>ivicli completion</c>.
/// </summary>
public static class CommandTreeWalker
{
    /// <summary>
    /// Returns the completion candidates for <paramref name="tokens"/>
    /// against <paramref name="root"/>. Token semantics match the way
    /// shells deliver words to a completion function: leading tokens
    /// are already-accepted positional / sub-command words and the
    /// trailing token (possibly empty) is the cursor word.
    /// </summary>
    public static ImmutableArray<string> Complete(Command root, IReadOnlyList<string> tokens)
    {
        // Walk into the deepest matching subcommand. Stop at the first
        // token that is not a recognised subcommand — that token (or the
        // trailing empty) becomes the prefix we filter against.
        var current = root;
        var index = 0;
        while (index < tokens.Count)
        {
            var token = tokens[index];
            var match = FindSubcommand(current, token);
            if (match is null)
            {
                break;
            }
            current = match;
            index++;
        }

        var prefix = index < tokens.Count ? tokens[index] : string.Empty;
        var builder = ImmutableArray.CreateBuilder<string>();

        // Options always available at the current command level (and hidden
        // ones are filtered out so users do not see internals).
        foreach (var option in current.Options)
        {
            if (option.Hidden)
            {
                continue;
            }
            if (option.Name.StartsWith(prefix, StringComparison.Ordinal))
            {
                builder.Add(option.Name);
            }
            foreach (var alias in option.Aliases)
            {
                if (alias.StartsWith(prefix, StringComparison.Ordinal))
                {
                    builder.Add(alias);
                }
            }
        }

        // If the prefix starts with `-` the user clearly wants an option;
        // skip subcommand suggestions to keep the candidate list tight.
        if (!prefix.StartsWith('-'))
        {
            foreach (var sub in current.Subcommands)
            {
                if (sub.Hidden)
                {
                    continue;
                }
                if (sub.Name.StartsWith(prefix, StringComparison.Ordinal))
                {
                    builder.Add(sub.Name);
                }
            }
        }

        // Stable sort gives deterministic output for snapshot tests and
        // matches how shell completion typically displays candidates.
        var sorted = builder.ToImmutable().Sort(StringComparer.Ordinal);
        return sorted;
    }

    /// <summary>
    /// Async overload of <see cref="Complete"/> that also consults the
    /// supplied <paramref name="registry"/> for dynamic candidates
    /// bound to the resolved command. Falls back to the structural
    /// candidates from <see cref="Complete"/> when no dynamic binding
    /// applies.
    /// </summary>
    public static async Task<ImmutableArray<string>> CompleteAsync(
        Command root,
        IReadOnlyList<string> tokens,
        CompletionRegistry registry,
        CancellationToken ct
    )
    {
        // Walk into the deepest matching subcommand exactly like the
        // synchronous version so the descent semantics stay identical.
        var current = root;
        var index = 0;
        while (index < tokens.Count)
        {
            var token = tokens[index];
            var match = FindSubcommand(current, token);
            if (match is null)
            {
                break;
            }
            current = match;
            index++;
        }

        var prefix = index < tokens.Count ? tokens[index] : string.Empty;

        // Static candidates first (subcommands + option names) using the
        // existing pure helper. We layer dynamic candidates on top so the
        // user always sees structural choices alongside the dynamic ones.
        var structural = Complete(
            current,
            prefix.Length > 0 ? new[] { prefix } : Array.Empty<string>()
        );

        // Resolve the slot to query. When the prefix is an option value
        // (the previous token is "--foo" or "--foo=value"), we honour
        // that option's slot; otherwise the slot is the next positional
        // argument the command declares.
        var slot = ResolveSlot(current, tokens, index);
        var dynamic = ImmutableArray<string>.Empty;
        if (slot is not null)
        {
            var completer = registry.Resolve(current, slot);
            if (completer is not null)
            {
                dynamic = await completer.CompleteAsync(prefix, ct);
            }
        }

        if (dynamic.IsDefaultOrEmpty)
        {
            return structural;
        }
        // Merge — structural may already include subcommands that
        // accidentally share a name with a device alias; keep both and
        // let the shell deduplicate on display.
        var merged = ImmutableArray.CreateBuilder<string>(structural.Length + dynamic.Length);
        merged.AddRange(structural);
        merged.AddRange(dynamic);
        return merged.ToImmutable().Sort(StringComparer.Ordinal);
    }

    private static string? ResolveSlot(Command command, IReadOnlyList<string> tokens, int index)
    {
        // Walk the trailing tokens (those past the descended subcommand
        // chain). If the immediately-preceding token is an option name
        // like "--device", we are completing that option's value.
        if (index > 0 && index <= tokens.Count)
        {
            var previous = index - 1;
            if (previous < tokens.Count)
            {
                var prev = tokens[previous];
                if (prev.StartsWith("--", StringComparison.Ordinal))
                {
                    return prev.TrimStart('-').Split('=')[0];
                }
            }
        }
        // Otherwise we are completing the next positional. v1 binds
        // dynamic completers to the first positional argument only —
        // commands that need slot-by-slot dispatch can extend the
        // registry later.
        if (command.Arguments.Count > 0)
        {
            return command.Arguments[0].Name;
        }
        return null;
    }

    /// <summary>
    /// Tokenises a raw command line into argv-style words for
    /// <see cref="Complete"/>. The first token (the program name) is
    /// dropped by the caller because shells already strip it before
    /// invoking the completion function.
    /// </summary>
    public static ImmutableArray<string> Tokenize(string line)
    {
        var builder = ImmutableArray.CreateBuilder<string>();
        var buffer = new System.Text.StringBuilder();
        var inQuote = false;
        foreach (var ch in line)
        {
            if (ch == '"')
            {
                inQuote = !inQuote;
                continue;
            }
            if (!inQuote && char.IsWhiteSpace(ch))
            {
                if (buffer.Length > 0)
                {
                    builder.Add(buffer.ToString());
                    buffer.Clear();
                }
                continue;
            }
            buffer.Append(ch);
        }
        // Preserve trailing partial token (including empty trailing word
        // when the cursor is after a space) so completers can suggest
        // candidates for the next position.
        if (buffer.Length > 0 || line.EndsWith(' '))
        {
            builder.Add(buffer.ToString());
        }
        return builder.ToImmutable();
    }

    private static Command? FindSubcommand(Command parent, string name)
    {
        foreach (var sub in parent.Subcommands)
        {
            if (sub.Name == name)
            {
                return sub;
            }
        }
        return null;
    }
}
