using System.Collections.Immutable;
using System.CommandLine;

namespace IviCli.Cli.Completion;

/// <summary>
/// Pure helper that walks a <see cref="Command"/> tree and resolves
/// completion candidates for a partially-typed command line. Used by
/// <c>ivicli __complete</c> to drive the bash / zsh / PowerShell stub
/// generated by <c>ivicli completion</c>.
/// </summary>
public static class CommandTreeWalker
{
    /// <summary>
    /// Returns the completion candidates for <paramref name="tokens"/>
    /// against <paramref name="root"/>. Token semantics match the way
    /// shells deliver words to a completion function: leading tokens
    /// are already-accepted positional / sub-command words and the
    /// trailing token (possibly empty) is the cursor word.
    /// </summary>
    public static ImmutableArray<string> Complete(Command root, IReadOnlyList<string> tokens)
    {
        // Walk into the deepest matching subcommand. Stop at the first
        // token that is not a recognised subcommand — that token (or the
        // trailing empty) becomes the prefix we filter against.
        var current = root;
        var index = 0;
        while (index < tokens.Count)
        {
            var token = tokens[index];
            var match = FindSubcommand(current, token);
            if (match is null)
            {
                break;
            }
            current = match;
            index++;
        }

        var prefix = index < tokens.Count ? tokens[index] : string.Empty;
        var builder = ImmutableArray.CreateBuilder<string>();

        // Options always available at the current command level (and hidden
        // ones are filtered out so users do not see internals).
        foreach (var option in current.Options)
        {
            if (option.Hidden)
            {
                continue;
            }
            if (option.Name.StartsWith(prefix, StringComparison.Ordinal))
            {
                builder.Add(option.Name);
            }
            foreach (var alias in option.Aliases)
            {
                if (alias.StartsWith(prefix, StringComparison.Ordinal))
                {
                    builder.Add(alias);
                }
            }
        }

        // If the prefix starts with `-` the user clearly wants an option;
        // skip subcommand suggestions to keep the candidate list tight.
        if (!prefix.StartsWith('-'))
        {
            foreach (var sub in current.Subcommands)
            {
                if (sub.Hidden)
                {
                    continue;
                }
                if (sub.Name.StartsWith(prefix, StringComparison.Ordinal))
                {
                    builder.Add(sub.Name);
                }
            }
        }

        // Stable sort gives deterministic output for snapshot tests and
        // matches how shell completion typically displays candidates.
        var sorted = builder.ToImmutable().Sort(StringComparer.Ordinal);
        return sorted;
    }

    /// <summary>
    /// Tokenises a raw command line into argv-style words for
    /// <see cref="Complete"/>. The first token (the program name) is
    /// dropped by the caller because shells already strip it before
    /// invoking the completion function.
    /// </summary>
    public static ImmutableArray<string> Tokenize(string line)
    {
        var builder = ImmutableArray.CreateBuilder<string>();
        var buffer = new System.Text.StringBuilder();
        var inQuote = false;
        foreach (var ch in line)
        {
            if (ch == '"')
            {
                inQuote = !inQuote;
                continue;
            }
            if (!inQuote && char.IsWhiteSpace(ch))
            {
                if (buffer.Length > 0)
                {
                    builder.Add(buffer.ToString());
                    buffer.Clear();
                }
                continue;
            }
            buffer.Append(ch);
        }
        // Preserve trailing partial token (including empty trailing word
        // when the cursor is after a space) so completers can suggest
        // candidates for the next position.
        if (buffer.Length > 0 || line.EndsWith(' '))
        {
            builder.Add(buffer.ToString());
        }
        return builder.ToImmutable();
    }

    private static Command? FindSubcommand(Command parent, string name)
    {
        foreach (var sub in parent.Subcommands)
        {
            if (sub.Name == name)
            {
                return sub;
            }
        }
        return null;
    }
}
