<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>IviCli.Backends.Local</RootNamespace>
    <AssemblyName>IviCli.Backends.Local</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\IviCli.Application\IviCli.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="IviFoundation.Visa" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>
</Project>
