<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>IviCli.Infrastructure</RootNamespace>
    <AssemblyName>IviCli.Infrastructure</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\IviCli.Application\IviCli.Application.csproj" />
  </ItemGroup>
</Project>
