<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>IviCli.Infrastructure.Tests</RootNamespace>
    <AssemblyName>IviCli.Infrastructure.Tests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\IviCli.Infrastructure\IviCli.Infrastructure.csproj" />
    <ProjectReference Include="..\IviCli.TestKit\IviCli.TestKit.csproj" />
  </ItemGroup>
</Project>
