<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>IviCli.Plugin.Tests</RootNamespace>
    <AssemblyName>IviCli.Plugin.Tests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\IviCli.Plugin\IviCli.Plugin.csproj" />
    <ProjectReference Include="..\IviCli.TestKit\IviCli.TestKit.csproj" />
  </ItemGroup>
</Project>
