<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>IviCli.Cli.Tests</RootNamespace>
    <AssemblyName>IviCli.Cli.Tests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\IviCli.Cli\IviCli.Cli.csproj" />
    <ProjectReference Include="..\IviCli.TestKit\IviCli.TestKit.csproj" />
  </ItemGroup>
</Project>
