<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>IviCli.Backends.Lxi</RootNamespace>
    <AssemblyName>IviCli.Backends.Lxi</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\IviCli.Application\IviCli.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Makaretu.Dns" />
    <PackageReference Include="Makaretu.Dns.Multicast" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>
</Project>
