<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>IviCli.Server.Tests</RootNamespace>
    <AssemblyName>IviCli.Server.Tests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\IviCli.Server\IviCli.Server.csproj" />
    <ProjectReference Include="..\..\src\IviCli.Backends.HiSlip\IviCli.Backends.HiSlip.csproj" />
    <ProjectReference Include="..\..\src\IviCli.Backends.Fake\IviCli.Backends.Fake.csproj" />
    <ProjectReference Include="..\IviCli.TestKit\IviCli.TestKit.csproj" />
  </ItemGroup>
</Project>
