<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>IviCli.Domain.Tests</RootNamespace>
    <AssemblyName>IviCli.Domain.Tests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\IviCli.Domain\IviCli.Domain.csproj" />
    <ProjectReference Include="..\IviCli.TestKit\IviCli.TestKit.csproj" />
  </ItemGroup>
</Project>
